### PR TITLE
Events

### LINKED ISSUE #34: Create, edit and delete Event
- [x] Create
- [x] Edit
- [x] Delete

### PR DESCRIPTION
**Pull request by svenpopping**
Fixes #34

### CODE REVIEW

**Comment by Icety** [comment]
- [ ] The text of the products underneath the edit event page are not aligned well with the buttons.
- [ ] The 'Add product' field gives a jquery error: Uncaught TypeError: Cannot read property 'length' of undefined.
- [ ] Clicking the edit button after a product on the edit event page, the page is redirected to events overview page.
- [ ] The autosave is nice, yet it's not clear that the website is autosaving, showing something when the website is autosaving would be nice, especially since the website refreshes after a save.
- [ ] When typing random text in the 'add product' field and pressing +, nothing happens.

**Comment by Icety** [comment]
Why isn't it possible to add products when adding a new event?

**Comment by svenpopping** [comment]
> The text of the products underneath the edit event page are not aligned well with the buttons.

Which text is this about?

**Comment by Icety** [comment]
c5d08a2f8e059779f37dbd3e12edc38a
The text on the left is not vertically aligned correctly with the buttons on the right.

**Comment by Icety** [comment]
LGTM

**Pull request merged**
