### PR TITLE
Add markdown descriptions

### PR DESCRIPTION
**Pull request by JoepdeJong**

### CODE REVIEW

**Comment by julian9499** [comment]
Is this still a WIP?

**Comment by JoepdeJong** [comment]
> Is this still a WIP?

yes. have to decide whether we will use the whole markdown script, or write a simple JS script that makes only using markdown links possible..

**Comment by julian9499** [comment]
I would suggest to make markdown as a whole possible

**Comment by JoepdeJong** [comment]
> I would suggest to make markdown as a whole possible

The part that will support markdown is highlighted in green. I think we do not need to make it possible to add headers or other stuff inside that part.

But maybe it is better to add a second button next to the add to cart button when a link and label are provided? See the suggestion in the screenshot.

Screenshot 2021-12-04 at 12 03 40
t.

**Pull request merged**
