### PR TITLE
Fix issue when creating postgresql tables, 'end' is a keyword

### PR DESCRIPTION
**Pull request by sanderploegsma**
Self-explanatory

### CODE REVIEW

**Comment by RickWieman** [comment]
LGTM.

**Comment by praseodym** [comment]
I'd prefer we use `@Column` to rename the column in the database instead of editing the Java field name.

**Comment by sanderploegsma** [comment]
Lol that never even occured to me. :joy:

**Comment by sanderploegsma** [comment]
:+1:

**Pull request merged**
