### PR TITLE
Add administration costs

### PR DESCRIPTION
**Pull request by robertdijk**
Add administration costs to each order. The value can be set in the application.yml. When the value of the products is 0, the administration costs will be 0.

This pr also shows the costs on the order overview page, and the shopping basked, and in the mail, and in the order on the admin panel. Basically all the places I could find.

Todo: 
- [x] Implement VAT for the administration costs.
- [ ] Test database migration

### CODE REVIEW

**Comment by robertdijk** [comment]
Robine said VAT does not have to be implemented since there is.not VAT on administration costs.

**Comment by robertdijk** [comment]
Can we test the database migration? or should we just try it?

**Comment by JoepdeJong** [comment]
> Can we test the database migration? or should we just try it?

at the moment, no, as there is no schema dump of the production environment available.

**Comment by 07joshua03** [comment]
Good tests, lgtm

would've been better to put in treasurer tab, but fine as is.

**Review by 07joshua03 — APPROVED** [review]

**Comment by JoepdeJong** [comment]
https://github.com/WISVCH/events/blob/master/src/main/resources/templates/admin/orders/view.html#L176-L181


gaat denk ik niet goed voor orders zonder kosten, dan hoeven de administratiekosten niet getoond te worden

**Pull request merged**
